name: CI

on: [push]

jobs:
  myjob:
    runs-on: ubuntu-18.04 # linux required if you want to use docker
    steps:
    - name: Build a docker image
      run: touch $HOME/stuff.txt
    - uses: actions/checkout@v1
    - run: docker build -t test:0.1 .
    - run: docker images
