name: CI

on: [push]

jobs:
  myjob:
    runs-on: ubuntu-18.04 # linux required if you want to use docker
    steps:
    # Checkout into the repository and build a docker image from Dockerfile
    - uses: actions/checkout@v1
    - run: git for-each-ref refs/tags --sort=-taggerdate --format='%(refname:short)' --count=1
    - run: |
        RELEASE_VERSION="$(git for-each-ref refs/tags --sort=-taggerdate --format='%(refname:short)' --count=1 2>&1)"
        echo ${RELEASE_VERSION}
        docker build -t quay.io/plysytsya/ebook-translator:${RELEASE_VERSION} .
        docker login quay.io --username  "${{ secrets.DOCKER_USERNAME }}" --password "${{ secrets.DOCKER_PASSWORD }}"
        docker push quay.io/plysytsya/ebook-translator:${RELEASE_VERSION}
