on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    runs:
      using: 'docker'
      image: 'Dockerfile'
    steps:
      run: |
        echo hello, world!
      
