name: CI

on: [push]

jobs:
  myjob:
    runs-on: ubuntu-18.04 # linux required if you want to use docker
    steps:
    # Checkout into the repository and build a docker image from Dockerfile
    - uses: actions/checkout@v1
    - run: docker build -t quay.io/plysytsya/ebook-translator:0.2 .
    - run: |
        docker login quay.io --username  "${{ secrets.DOCKER_USERNAME }}" --password "${{ secrets.DOCKER_PASSWORD }}"
        docker push quay.io/plysytsya/ebook-translator:0.2
